version: "3.3"
services:
  front:
    build:
        context: frontend
        dockerfile: Dockerfile
    volumes:
        - './frontend/dist:/tmp/deploy'
    networks:
        - internal

  mongo:
    image: mongo:4.4.1-bionic
    restart: always
    networks:
      - internal

  back:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - internal

  nginx:
    image: nginx:1.17.6
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/deploy/:/frontend
    ports:
      - "80:80"
    links:
      - back
    networks:
      - internal

networks:
  internal:
    driver: bridge


